model_type: "time_series"
feature_version: "v1.1_before_.1_after_0"
description: "DEMO"

include_features:
  segments: false
  angles: true
  velocities: false
  accelerations: false

phases:
  windup: false
  release: true
  follow: false

window:
  pre_seconds: 0.1
  post_seconds: 0.0

padding:
  mode: "pad"   # "pad" or "drop"
  pad_value: null   # -> NaN
  emit_mask: true

stats:
  windup:    { min: false, max: false, mean: false, std: false, range: false, total_change: false }
  release:   { release_value: true }
  follow:    { min: false, max: false, mean: false, std: false, range: false, total_change: false }

angles:
  knee_flex_r: { include: true }
  knee_flex_l: { include: true }
  ankle_flex_r: { include: true }
  ankle_flex_l: { include: true }
  elbow_flex_r: { include: true }
  elbow_flex_l: { include: true }
  hip_flex_r: { include: true }
  hip_flex_l: { include: true }
  shoulder_flex_r: { include: true }
  shoulder_flex_l: { include: true }
  arm_flex_r: { include: true }
  arm_flex_l: { include: true }
