# Session Information
athlete: "alton_overson"
session: "session_04"

# Stereo Calibration Parameters
inner_corners: [9,7] # [5,4] session 1 session 3: 9,7   # inner corners (columns, rows)
square_size_cm: 5.67 # 3.4 session 1 session 3: 5.67       # Size of one square in cm
calibrate_every: 50        # How often to update calibration preview
success_window: 50         # Rolling detection success window
min_square_px: 40

# Video Parameters
original_frame_width: 1280          # Full camera resolution width
original_frame_height: 720          # Full camera resolution height
crop_size: [640, 640]      # Crop size (width, height)

# Camera Indices
left_cam_index: 2
right_cam_index: 0
third_cam_index: 4

# FPS settings
player_tracking_fps: 60
ball_tracking_fps: 30

# Feature Engineering 
# include_3d_angles: true
# include_3d_velocities: false
# include_3d_accelerations: false


# Detection Thresholds
threshold_detect: 0.7      # Success rate threshold for stability
threshold_fl: 10           # Max allowed focal length diff (px)
threshold_pp: 20           # Max allowed principal point diff (px)


paths:
  # Analysis
  analysis: "data/{athlete}/{session}/analysis"
  datasets: "data/{athlete}/{session}/analysis/datasets"
  experiments: "data/{athlete}/{session}/analysis/datasets/experiments"
  analysis_plots: "data/{athlete}/{session}/analysis/plots"
  models: "data/{athlete}/{session}/analysis/models"

  # Calibration
  calibration: "data/{athlete}/{session}/calibration"
  calib_images: "data/{athlete}/{session}/calibration/calib_images"
  calib_pairs: "data/{athlete}/{session}/calibration/calib_images/pairs"
  calib_mono_left: "data/{athlete}/{session}/calibration/calib_images/mono_left"
  calib_mono_right: "data/{athlete}/{session}/calibration/calib_images/mono_right"
  mono_intrinsics: "data/{athlete}/{session}/calibration/mono_intrinsics"
  stereo_calibration: "data/{athlete}/{session}/calibration/stereo_calibration"

  # Metrics
  metrics: "data/{athlete}/{session}/metrics"
  keypoints_2d: "data/{athlete}/{session}/metrics/2d_keypoints"
  keypoints_3d: "data/{athlete}/{session}/metrics/3d_keypoints"
  angles: "data/{athlete}/{session}/metrics/3d_angles"
  shortened_angles: "experiments/"
  velocities: "data/{athlete}/{session}/metrics/3d_velocities"
  accelerations: "data/{athlete}/{session}/metrics/3d_accelerations"
  ball_tracking_metrics: "data/{athlete}/{session}/metrics/ball_tracking_metrics"
  phases: "data/{athlete}/{session}/metrics/freethrow_phases.csv"

  #Features
  features: "data/{athlete}/{session}/analysis/datasets/features"
  summary_stats: "data/{athlete}/{session}/features/summary_stats"
  time_series: "data/{athlete}/{session}/features/time_series"


  # Videos
  videos: "data/{athlete}/{session}/videos"
  ball_tracking: "data/{athlete}/{session}/videos/ball_tracking"
  ball_tracking_raw: "data/{athlete}/{session}/videos/ball_tracking/raw"
  player_tracking: "data/{athlete}/{session}/videos/player_tracking"
  player_tracking_2d: "data/{athlete}/{session}/videos/player_tracking/2d"
  player_tracking_raw: "data/{athlete}/{session}/videos/player_tracking/raw"
  player_tracking_left: "data/{athlete}/{session}/videos/player_tracking/raw/left"
  player_tracking_right: "data/{athlete}/{session}/videos/player_tracking/raw/right"
  player_tracking_sync: "data/{athlete}/{session}/videos/player_tracking/synchronized"

  # Models 
  experiments: "experiments"
  feature_sets: "experiments/feature_sets"
  runs: "experiments/runs"

