athletes:
  alton_overson:
    
    session_01:
      hoop_regions: # Get these from create_hoop_regions.py
        upper: [[634, 212], [685, 272]]
        lower: [[634, 272], [685, 352]]
      hsv_ranges:     
        lower: [0, 75, 50]
        upper: [12, 230, 200]
      
      ball_area_px: {min: 400, max: 4000}
      circularity_min: .7
      fill_ratio_min: .65

      min_motion: 5
      erode_iters: 2
      dilate_iters: 4
      blur_ksize: 1
    

    session_02:
      #values from create_hoop_regions.py
      hoop_regions:
        upper: [[631, 174], [686, 234]]
        lower: [[631, 234], [686, 314]]
      
      #values from tune_ball_detection.py
      hsv_ranges:     
        lower: [0, 75, 50]
        upper: [12, 230, 200]
      
      ball_area_px: {min: 400, max: 4000}
      circularity_min: .7
      fill_ratio_min: .65

      min_motion: 5
      erode_iters: 2
      dilate_iters: 4
      blur_ksize: 1


    session_03:
      #values from create_hoop_regions.py
      hoop_regions:
        upper: [[811, 194], [875, 254]]
        lower: [[811, 254], [875, 334]]
      
      #values from tune_ball_detection.py
      hsv_ranges:
        lower: [0, 46, 0]
        upper: [8, 180, 255]

      ball_area_px: {min: 400, max: 4000}
      circularity_min: .65
      fill_ratio_min: .65

      min_motion: 5
      erode_iters: 4
      dilate_iters: 6
      blur_ksize: 1

    # TODO these values are just copied from session 3
    session_04:
      #values from create_hoop_regions.py
      hoop_regions:
        upper: [[686, 220], [732, 280]]
        lower: [[686, 280], [732, 360]]
      
      #values from tune_ball_detection.py
      hsv_ranges:
        lower: [0, 46, 0]
        upper: [8, 180, 255]

      ball_area_px: {min: 400, max: 4000}
      circularity_min: .65
      fill_ratio_min: .65

      min_motion: 5
      erode_iters: 4
      dilate_iters: 6
      blur_ksize: 1

  kenny_williams:
    
    session_with_kymber:
      hoop_regions: # Get these from create_hoop_regions.py
        upper: [[634, 212], [685, 272]]
        lower: [[634, 272], [685, 352]]
      hsv_ranges:     
        lower: [0, 75, 50]
        upper: [12, 230, 200]
      
      ball_area_px: {min: 400, max: 4000}
      circularity_min: .7
      fill_ratio_min: .65

      min_motion: 5
      erode_iters: 2
      dilate_iters: 4
      blur_ksize: 1


  tyler_haws:
    
    session_with_tyler_haws_gym:
      hoop_regions: # Get these from create_hoop_regions.py
        upper: [[634, 212], [685, 272]]
        lower: [[634, 272], [685, 352]]
      hsv_ranges:     
        lower: [0, 75, 50]
        upper: [12, 230, 200]
      
      ball_area_px: {min: 400, max: 4000}
      circularity_min: .7
      fill_ratio_min: .65

      min_motion: 5
      erode_iters: 2
      dilate_iters: 4
      blur_ksize: 1