"""
Title: split_csv_by_group.py 

Purpose:
    Splits a kinematic summary CSV file (release_summary.csv) into separate CSV files based on joint groups
    (core, arms, legs). This helps with modular analysis and cleaner data management.

Prerequisites:
    - A CSV file generated by process_mot_to_csv.py (release_summary.csv) located in the specified input path

Output:
    - CSV files for each joint group (core_angles.csv, arms_angles.csv, legs_angles.csv)

Usage:
    Run this script after generating the release_summary.csv file.
"""

import pandas as pd
from pathlib import Path

# Input
release_summary_path = Path("../data/freethrows3/release_summary.csv")

# Output paths
core_path = release_summary_path.parent / "core_angles.csv"
arms_path = release_summary_path.parent / "arms_angles.csv"
legs_path = release_summary_path.parent / "legs_angles.csv"

# Load the release summary
df = pd.read_csv(release_summary_path)

# Define groups
pelvis = ['pelvis_tilt', 'pelvis_list', 'pelvis_rotation']
hips_r = ['hip_flexion_r', 'hip_adduction_r', 'hip_rotation_r']
hips_l = ['hip_flexion_l', 'hip_adduction_l', 'hip_rotation_l']
lumbar = ['lumbar_extension', 'lumbar_bending', 'lumbar_rotation']
core_cols = pelvis + hips_r + hips_l + lumbar

arms_r = ['arm_flex_r', 'arm_add_r', 'arm_rot_r', 'elbow_flex_r', 'pro_sup_r']
arms_l = ['arm_flex_l', 'arm_add_l', 'arm_rot_l', 'elbow_flex_l', 'pro_sup_l']
arms_cols = arms_r + arms_l

legs_r = ['knee_angle_r', 'ankle_angle_r', 'subtalar_angle_r', 'mtp_angle_r']
legs_l = ['knee_angle_l', 'ankle_angle_l', 'subtalar_angle_l', 'mtp_angle_l']
legs_cols = legs_r + legs_l

# Always include identifying columns
id_cols = ['file', 'clip_name', 'outcome']

# Save subsets
if all(col in df.columns for col in core_cols):
    df[id_cols + core_cols].to_csv(core_path, index=False)

if all(col in df.columns for col in arms_cols):
    df[id_cols + arms_cols].to_csv(arms_path, index=False)

if all(col in df.columns for col in legs_cols):
    df[id_cols + legs_cols].to_csv(legs_path, index=False)

print("CSV files split into: core_angles.csv, arms_angles.csv, legs_angles.csv")
